version: "3.3"

services:

  db:
    image: hexly/postgres-alpine  
    ports:
      - "5432:5432"
    volumes:
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      - POSTGRES_DB=healenium
      - POSTGRES_USER=healenium_user
      - POSTGRES_PASSWORD=jesus
    networks:
      - healenium

  healenium:
    image: healenium/hlm-backend:3.2.3
    ports:
      - "7878:7878"
    links:
      - db
    restart: always
    environment:
      - SPRING_CONTAINER_NAME=healenium
      - SPRING_POSTGRES_DB=healenium
      - SPRING_POSTGRES_USER=healenium_user
      - SPRING_POSTGRES_PASSWORD=jesus
      - SPRING_POSTGRES_URL=jdbc:postgresql://localhost:5432/healenium?currentSchema=healenium
    networks:
      - healenium

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.1
    restart: on-failure
    ports:
      - "8000:8000"

networks:
  healenium:
